# Generated by Django 3.0.1 on 2020-01-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Works',
                'db_table': 'tbl_work',
            },
        ),
    ]
