# Generated by Django 3.0.1 on 2020-01-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
    ]
